// <auto-generated />
using DataLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLibrary.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20220208173914_addRestaurantsHierarchy")]
    partial class addRestaurantsHierarchy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyDataModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Games"
                        });
                });

            modelBuilder.Entity("MyDataModels.Convenience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Conveniences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Sit Down"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Take Out"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Fast Food"
                        });
                });

            modelBuilder.Entity("MyDataModels.Cuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cuisines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Italian"
                        },
                        new
                        {
                            Id = 2,
                            Type = "American"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Mexican"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Korean"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Chinese"
                        });
                });

            modelBuilder.Entity("MyDataModels.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "The Sword of Shannara"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Top Gun"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Name = "World of Tanks"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Inception"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Tenet"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Wordle"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Programming in C#"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Name = "Pro GIT"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Batman Begins"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Man of Steel"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Monopoly"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "Suburbia"
                        });
                });

            modelBuilder.Entity("MyDataModels.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ConvenienceId")
                        .HasColumnType("int");

                    b.Property<int>("CuisineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConvenienceId");

                    b.HasIndex("CuisineId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConvenienceId = 1,
                            CuisineId = 1,
                            Name = "Olive Garden",
                            Price = 2
                        },
                        new
                        {
                            Id = 2,
                            ConvenienceId = 3,
                            CuisineId = 3,
                            Name = "Taco Bell",
                            Price = 1
                        },
                        new
                        {
                            Id = 3,
                            ConvenienceId = 1,
                            CuisineId = 2,
                            Name = "Ruth's Chriss",
                            Price = 3
                        },
                        new
                        {
                            Id = 4,
                            ConvenienceId = 2,
                            CuisineId = 2,
                            Name = "Cookout",
                            Price = 1
                        });
                });

            modelBuilder.Entity("MyDataModels.Item", b =>
                {
                    b.HasOne("MyDataModels.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyDataModels.Restaurant", b =>
                {
                    b.HasOne("MyDataModels.Convenience", "Convenience")
                        .WithMany("Restaurants")
                        .HasForeignKey("ConvenienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDataModels.Cuisine", "Cuisine")
                        .WithMany("Restaurants")
                        .HasForeignKey("CuisineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenience");

                    b.Navigation("Cuisine");
                });

            modelBuilder.Entity("MyDataModels.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyDataModels.Convenience", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("MyDataModels.Cuisine", b =>
                {
                    b.Navigation("Restaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
